### PR TITLE
chore: fix small typo

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Bump. This is still relevant.

**Comment by DanielRuf** [comment]
Bump.

**Comment by JoelEinbinder** [comment]
This is just a mirror, we only accept patches upstream in Chromium.

**Comment by DanielRuf** [comment]
That's very unfortunate. Thanks for the information.

**Comment by DanielRuf** [comment]
Please contact GitHub support and let them mark this repository as mirror.
Disabling PRs in the settings probably also makes sense.

**Comment by JoelEinbinder** [comment]
https://github.com/dear-github/dear-github/issues/84

**Pull request closed without merging**
